const api = await import(new URL("../../dist/lite/index.js", import.meta.url));

const { getPinnedSuiVersion, updateMovePackagePublication } = api;

const chainId = "test-chain-id";
const network = "testnet";
const packageV1 = address("0x111");
const packageV2 = address("0x222");
const upgradeCap = address("0x333");
const mainnetPackage = address("0x444");
const toolchainVersion = await getPinnedSuiVersion();
const publishedTomlHeader = `# Generated by Move
# This file contains metadata about published versions of this package in different environments
# This file SHOULD be committed to source control
`;

function address(value) {
  return `0x${value.replace(/^0x/i, "").padStart(64, "0").toLowerCase()}`;
}

function prepared(intent) {
  return {
    intent,
    modules: [],
    dependencies: [],
    digest: [],
    moveLock: "[move]\nversion = 4\n",
    environment: network,
    ...(intent === "upgrade" ? { packageId: packageV1 } : {}),
  };
}

function transactionResult({
  packageId,
  version,
  includeUpgradeCap = true,
  upgradeCapType = "0x2::package::UpgradeCap",
}) {
  return {
    $kind: "Transaction",
    Transaction: {
      digest: "7TeStDigest",
      status: { success: true, error: null },
      effects: {
        changedObjects: [
          {
            objectId: packageId,
            outputState: "PackageWrite",
            outputVersion: String(version),
            idOperation: "Created",
          },
          ...(includeUpgradeCap
            ? [
                {
                  objectId: upgradeCap,
                  outputState: "ObjectWrite",
                  outputVersion: String(version),
                  idOperation: "Created",
                },
              ]
            : []),
        ],
      },
      objectTypes: includeUpgradeCap ? { [upgradeCap]: upgradeCapType } : {},
    },
  };
}

function assertIncludes(text, expected, label) {
  if (!text.includes(expected)) {
    throw new Error(`${label}: missing '${expected}'\n${text}`);
  }
}

function assertNotIncludes(text, expected, label) {
  if (text.includes(expected)) {
    throw new Error(`${label}: unexpected '${expected}'\n${text}`);
  }
}

function publishedSection(text, name) {
  const marker = `[published.${name}]`;
  const start = text.indexOf(marker);
  if (start === -1) {
    throw new Error(`missing ${marker}\n${text}`);
  }
  const next = text.indexOf("\n[published.", start + marker.length);
  return next === -1 ? text.slice(start) : text.slice(start, next);
}

function expectFailure(result, label) {
  if (!("error" in result)) {
    throw new Error(`${label}: expected failure`);
  }
  if (result.category !== "input_validation") {
    throw new Error(`${label}: expected input_validation failure`);
  }
}

const publishUpdate = await updateMovePackagePublication({
  files: {},
  prepared: prepared("publish"),
  result: transactionResult({ packageId: packageV1, version: 1 }),
  network,
  chainId,
});

if ("error" in publishUpdate) {
  throw new Error(`publish update failed: ${publishUpdate.error}`);
}
assertIncludes(
  publishUpdate.publishedToml,
  `[published.${network}]`,
  "publish"
);
assertIncludes(
  publishUpdate.publishedToml,
  `chain-id = "${chainId}"`,
  "publish"
);
assertIncludes(
  publishUpdate.publishedToml,
  `published-at = "${packageV1}"`,
  "publish"
);
assertIncludes(
  publishUpdate.publishedToml,
  `original-id = "${packageV1}"`,
  "publish"
);
assertIncludes(publishUpdate.publishedToml, `version = 1`, "publish");
assertIncludes(
  publishUpdate.publishedToml,
  `toolchain-version = "${toolchainVersion}"`,
  "publish"
);
assertIncludes(
  publishUpdate.publishedToml,
  `build-config = { flavor = "sui", edition = "2024" }`,
  "publish"
);
assertIncludes(
  publishUpdate.publishedToml,
  `upgrade-capability = "${upgradeCap}"`,
  "publish"
);
if (publishUpdate.files["Published.toml"] !== publishUpdate.publishedToml) {
  throw new Error("publish update should update returned files snapshot");
}
if ("Move.lock" in publishUpdate.files) {
  throw new Error("publication update should not create Move.lock");
}
if ("moveLock" in publishUpdate) {
  throw new Error("publication update should not return moveLock");
}

const filesWithMoveLock = { "Move.lock": "[move]\nversion = 4\n" };
const publishUpdateWithMoveLock = await updateMovePackagePublication({
  files: filesWithMoveLock,
  prepared: prepared("publish"),
  result: transactionResult({ packageId: packageV1, version: 1 }),
  network,
  chainId,
});
if ("error" in publishUpdateWithMoveLock) {
  throw new Error(
    `publish update with Move.lock failed: ${publishUpdateWithMoveLock.error}`
  );
}
if (
  publishUpdateWithMoveLock.files["Move.lock"] !==
  filesWithMoveLock["Move.lock"]
) {
  throw new Error("publication update should preserve existing Move.lock");
}

const existingFiles = {
  "Published.toml": `${publishedTomlHeader}
[published.mainnet]
chain-id = "main-chain"
published-at = "${mainnetPackage}"
original-id = "${mainnetPackage}"
version = 9

[published.testnet]
chain-id = "${chainId}"
published-at = "${packageV1}"
original-id = "${packageV1}"
version = 1
toolchain-version = "${toolchainVersion}"
build-config = { flavor = "sui", edition = "2024" }
upgrade-capability = "${upgradeCap}"
`,
};

const upgradeUpdate = await updateMovePackagePublication({
  files: existingFiles,
  prepared: prepared("upgrade"),
  result: transactionResult({
    packageId: packageV2,
    version: 2,
    includeUpgradeCap: false,
  }),
  network,
  chainId,
});

if ("error" in upgradeUpdate) {
  throw new Error(`upgrade update failed: ${upgradeUpdate.error}`);
}
assertIncludes(
  upgradeUpdate.publishedToml,
  `published-at = "${mainnetPackage}"`,
  "upgrade preserves mainnet"
);
assertIncludes(
  upgradeUpdate.publishedToml,
  `published-at = "${packageV2}"`,
  "upgrade"
);
assertIncludes(
  upgradeUpdate.publishedToml,
  `original-id = "${packageV1}"`,
  "upgrade"
);
assertIncludes(upgradeUpdate.publishedToml, `version = 2`, "upgrade");
assertIncludes(
  upgradeUpdate.publishedToml,
  `upgrade-capability = "${upgradeCap}"`,
  "upgrade"
);
assertNotIncludes(
  publishedSection(upgradeUpdate.publishedToml, "mainnet"),
  "build-config",
  "upgrade preserves missing build-config"
);
assertIncludes(
  publishedSection(upgradeUpdate.publishedToml, "testnet"),
  `build-config = { flavor = "sui", edition = "2024" }`,
  "upgrade selected env build config"
);

const dottedNetwork = "qa.env";
const dottedUpdate = await updateMovePackagePublication({
  files: {},
  prepared: prepared("publish"),
  result: transactionResult({ packageId: packageV1, version: 1 }),
  network: dottedNetwork,
  chainId,
});
if ("error" in dottedUpdate) {
  throw new Error(
    `dotted environment publish update failed: ${dottedUpdate.error}`
  );
}
assertIncludes(
  dottedUpdate.publishedToml,
  `[published."${dottedNetwork}"]`,
  "dotted environment"
);
assertNotIncludes(
  dottedUpdate.publishedToml,
  `[published.${dottedNetwork}]`,
  "dotted environment"
);

expectFailure(
  await updateMovePackagePublication({
    files: { "Published.toml": publishedTomlHeader },
    prepared: prepared("publish"),
    result: transactionResult({
      packageId: packageV1,
      version: 1,
      includeUpgradeCap: false,
    }),
    network,
    chainId,
  }),
  "publish without UpgradeCap"
);

expectFailure(
  await updateMovePackagePublication({
    files: {},
    prepared: prepared("upgrade"),
    result: transactionResult({
      packageId: packageV2,
      version: 2,
      includeUpgradeCap: false,
    }),
    network,
    chainId,
  }),
  "upgrade without Published.toml"
);

expectFailure(
  await updateMovePackagePublication({
    files: { "Published.toml": publishedTomlHeader },
    prepared: prepared("upgrade"),
    result: transactionResult({
      packageId: packageV2,
      version: 2,
      includeUpgradeCap: false,
    }),
    network,
    chainId,
  }),
  "upgrade without existing record"
);

expectFailure(
  await updateMovePackagePublication({
    files: { "Published.toml": publishedTomlHeader },
    prepared: prepared("publish"),
    result: transactionResult({
      packageId: packageV1,
      version: 1,
      upgradeCapType: "0xabc::package::UpgradeCap",
    }),
    network,
    chainId,
  }),
  "publish with non-Sui UpgradeCap"
);

expectFailure(
  await updateMovePackagePublication({
    files: { "Published.toml": publishedTomlHeader },
    prepared: prepared("publish"),
    result: { $kind: "FailedTransaction", FailedTransaction: {} },
    network,
    chainId,
  }),
  "failed transaction"
);

console.log("[OK] publication update uses external execution results");
